### ISSUE TITLE
Inference code?

### ISSUE THREAD

**Issue by echo840** [NVlabs/RADIO#57]
When I run the code
```python
import torch
from PIL import Image
from transformers import AutoModel, CLIPImageProcessor

# hf_repo = "nvidia/E-RADIO" # For E-RADIO.
hf_repo = "nvidia/RADIO" # For RADIO.

image_processor = CLIPImageProcessor.from_pretrained(hf_repo)
model = AutoModel.from_pretrained(hf_repo, trust_remote_code=True)
model.eval().cuda()

image = Image.open('./assets/radio.png').convert('RGB')
pixel_values = image_processor(images=image, return_tensors='pt', do_resize=True).pixel_values
pixel_values = pixel_values.cuda()

summary, features = model(pixel_values)
```
I encountered an error, how can I solve it? Should I do something with image_processor?
![image](https://github.com/NVlabs/RADIO/assets/87795401/d548f89e-e957-4933-a303-7c7a093833db)

**Comment by gheinrich** [comment]
Hello, this code resizes the shortest edge of the image to 432 pixels and adjusts the longest edge so as to preserve the aspect ratio. In your case this leads to an image size of 432x985. The error occurs because the width (985) of the input image is not a multiple of the patch size (16).

You can fix this with a center crop. Take a look at the [CLIPImageProcessor API](https://github.com/huggingface/transformers/blob/main/src/transformers/models/clip/image_processing_clip.py#L52). One example invocation would be:

```
pixel_values = image_processor(
    images=image,
    return_tensors='pt',
    do_resize=True,
    do_center_crop=True,
    crop_size={'width': 976, 'height': 432).pixel_values
```
