### ISSUE TITLE
How is `max_resolution` used?

### ISSUE THREAD

**Issue by collinmccarthy** [NVlabs/RADIO#74]
Hello,

I see `max_resolution` referenced in a lot of places but I don't see it actually used anywhere currently. I'm assuming it was used during training? 

Can you explain how you used it and why you needed it? I'm assuming this value has some "assumptions" associated with it, e.g. fp16/bfloat16, a GPU with <=80 GB, batch size of 1, training mode, etc. Can you list describe or list what those assumptions are in case those change for some users?

And if I'm just totally missing how it's connected to the current codebase I apologize. 

Thanks,
-Collin

**Comment by mranzinger** [comment]
It represents the resolution of the position embedding tensor. Specifically, the position embeddings are 128x128, which with a patch size of 16 comes out to 2048. It turns out that RADIOv2 is able to extrapolate past 2048 without too much degradation, but, that's at least what `max_resolution` means.

**Comment by collinmccarthy** [comment]
Ah, got it. Thank you, makes sense.
