### ISSUE TITLE
Making sense of feature dimensions

### ISSUE THREAD

**Issue by OasisArtisan** [NVlabs/RADIO#80]
Thanks for sharing your great work.

I am trying to make sense of the summary feature dimension outputted by RADIO2.5-b

The model outputs a (1,2304) summary feature.
Which is 3x768. So I thought maybe you are using 3 cls tokens. But model.num_summary_tokens shows 8 and model.model.patch_generator.cls_token.num_tokens shows 4.

model.summary_idxs shows 3 idxs inline with my 3 cls token understanding.

But to add to my confusion, the summary adaptor heads take in a 768 feature vector as opposed to 2304.
It seems each adaptor operates on a separate single cls token.

I may be misunderstanding the whole structure.

Your clarification is appreciated.

**Comment by OasisArtisan** [comment]
Ok what I gathered so far.

There are 4 register tokens following the work of Timothee Darcet, and 4 cls tokens (one for each adaptor head).

And we are only choosing the first 3 cls tokens as our summary representation. The cls token corresponding to SAM is ignored.

**Comment by mranzinger** [comment]
Yep, you're exactly right with your last comment.

There are 3 cls tokens that participate in the final summary feature (DFN CLIP, SigLIP, and DINOv2). That's why `model.summary_idxs` has 3 entries, corresponding to those teachers.

```
model.model.patch_generator.cls_token.num_tokens == 4
```
Because we technically have a cls token for SAM, but it's untrained and not used. (That's a limitation of the implementation, as we also have a SAM summary head that probably has 0 weights)

> It seems each adaptor operates on a separate single cls token.
Yeah, each adaptor has its own token. Empirically this worked better than a single token that's shared across all teachers. Presumably because the summary representation is fairly different.

So yeah, nice work decrypting those settings.

**Comment by OasisArtisan** [comment]
I see. Makes a lot of sense. Thank you !
